# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "1aa1042261c5e3bf1c7949166a2ac88a"
name = "Flexible Product Discounts"
application_url = "https://product-discount-js-misty-field-1960.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
scopes = "write_products,read_products,write_discounts"

[auth]
redirect_urls = [
  "https://product-discount-js-misty-field-1960.fly.dev/auth/callback",
  "https://product-discount-js-misty-field-1960.fly.dev/auth/shopify/callback",
  "https://product-discount-js-misty-field-1960.fly.dev/api/auth/callback"
]
